FROM soleng.jfrog.io/matthewy-ci-containers/python:3

COPY . /app
WORKDIR /app

RUN pip install pipenv --extra-index-url=${{secrets.PYPI_URI}}
      
RUN pipenv install --system --deploy

CMD ["python", "./src/metar.py"]