# This is a basic workflow to help you get started with Actions

name: Run metar unit tests
on:
  workflow_dispatch:

# Controls when the workflow will run
# on:
#   # Triggers the workflow on push or pull request events but only for the "main" and dev branches
#   push:
#     branches: [ "dev", "main" ]
#   pull_request:
#     branches: [ "dev", "main" ]
#   workflow_dispatch:
  

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install pyenv
        run: curl https://pyenv.run | bash
      - name: Install pipenv
        run: pip install pipenv
      - name: Install python virtual environment
        run: |
          pipenv install --dev --verbose
      - name: Run python tests
        run: | 
          pipenv run  python ./tests.py

      # Runs a set of commands using the runners shell
      - name: Configure the Python environment
        run: |
          cd src
          python ./metar.py
